"""baseline schema

Revision ID: 9e687de34bce
Revises:
Create Date: 2026-07-06 22:50:57.179215+00:00

Single baseline migration for the entire application schema: every table,
index, and constraint in ``Base.metadata``, plus the Postgres row-level
security (``tenant_isolation``) policies that pin tenanted tables to
``current_setting('app.current_tenant')`` (ADR-0011 / ADR-0014). RLS is
applied on Postgres only; the SQLite test path no-ops. ``DateTime`` columns
are the SQL rendering of the app's ``UTCDateTime`` decorator (see
backend/alembic/env.py) — the decorator only affects Python-side binding.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "9e687de34bce"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _is_postgres() -> bool:
    return op.get_bind().dialect.name == "postgresql"


# Tenanted tables protected by the `tenant_isolation` RLS policy (Postgres
# only; the SQLite test path no-ops). `tenants` is intentionally exempt — every
# other table FKs to it and the current-tenant lookup must read it before the
# `app.current_tenant` GUC is set. `work_schedules` carries a `tenant_id` but
# was never placed under RLS in the original schema history; that is preserved
# here rather than changed.
_RLS_TENANTED_TABLES = (
    "issues",
    "transitions",
    "time_slices",
    "metrics_issue",
    "metrics_status_window",
    "alerts",
    "alert_rules",
    "wip_limits",
    "sprints",
    "issue_sprints",
    "alert_delivery_destinations",
    "alert_rule_destinations",
    "alert_fires",
)


def _enable_rls(table: str) -> None:
    op.execute(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY')
    # FORCE so the policy applies even to the table owner.
    op.execute(f'ALTER TABLE "{table}" FORCE ROW LEVEL SECURITY')
    op.execute(
        f"""
        CREATE POLICY tenant_isolation ON "{table}"
        USING (tenant_id = current_setting('app.current_tenant', true))
        WITH CHECK (tenant_id = current_setting('app.current_tenant', true))
        """
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("client_key", sa.String(), nullable=False),
        sa.Column("cloud_id", sa.String(), nullable=True),
        sa.Column("base_url", sa.String(), nullable=False),
        sa.Column("display_url", sa.String(), nullable=True),
        sa.Column("product_type", sa.String(), nullable=False),
        sa.Column("forge_installation_id", sa.String(), nullable=True),
        sa.Column("plan", sa.String(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("installed_at", sa.DateTime(), nullable=False),
        sa.Column("last_sync_at", sa.DateTime(), nullable=True),
        sa.Column("active_statuses", sa.JSON(), nullable=True),
        sa.Column("done_statuses", sa.JSON(), nullable=True),
        sa.Column("terminal_statuses", sa.JSON(), nullable=True),
        sa.Column("external_blocking_statuses", sa.JSON(), nullable=True),
        sa.Column("independent_done_terminal_lists", sa.Boolean(), nullable=True),
        sa.Column("backfill_status", sa.String(), nullable=True),
        sa.Column("backfill_total_issues", sa.Integer(), nullable=True),
        sa.Column("backfill_processed_issues", sa.Integer(), nullable=True),
        sa.Column("backfill_started_at", sa.DateTime(), nullable=True),
        sa.Column("backfill_completed_at", sa.DateTime(), nullable=True),
        sa.Column("backfill_next_page_token", sa.String(), nullable=True),
        sa.Column("backfill_error", sa.Text(), nullable=True),
        sa.Column("bottleneck_time_ratio_threshold", sa.Float(), nullable=True),
        sa.Column("bottleneck_wip_ratio_threshold", sa.Float(), nullable=True),
        sa.Column("bottleneck_throughput_delta_threshold", sa.Float(), nullable=True),
        sa.Column("story_points_field_id", sa.String(), nullable=True),
        sa.Column("sprint_field_id", sa.String(), nullable=True),
        sa.Column("backfill_acknowledged_at", sa.DateTime(), nullable=True),
        sa.Column("admin_contact_email", sa.String(), nullable=True),
        sa.Column("last_failure_digest_at", sa.DateTime(), nullable=True),
        sa.Column("active_work_schedule_id", sa.Integer(), nullable=True),
        sa.Column("forge_env_id", sa.String(), nullable=True),
        sa.Column("recompute_status", sa.String(), nullable=True),
        sa.Column("recompute_rows_processed", sa.Integer(), nullable=True),
        sa.Column("recompute_started_at", sa.DateTime(), nullable=True),
        sa.Column("recompute_error", sa.Text(), nullable=True),
        # `active_work_schedule_id` is an unconstrained Integer at the DB level
        # — NOT a DB foreign key. `tenants` and `work_schedules` reference each
        # other, so a DB-level FK here would force a circular CREATE TABLE order
        # (and SQLite can't add an FK via ALTER anyway). The relationship is
        # enforced in the SQLAlchemy model; the DB column is intentionally bare.
        sa.PrimaryKeyConstraint("client_key"),
        sa.UniqueConstraint("forge_installation_id"),
    )
    with op.batch_alter_table("tenants", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tenants_cloud_id"), ["cloud_id"], unique=False)

    op.create_table(
        "work_schedules",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("timezone", sa.String(), nullable=False),
        sa.Column("working_days_mask", sa.Integer(), nullable=False),
        sa.Column("work_start_time", sa.String(), nullable=False),
        sa.Column("work_end_time", sa.String(), nullable=False),
        sa.Column("holidays", sa.JSON(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.client_key"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "name", name="uq_work_schedules_tenant_name"),
    )
    op.create_table(
        "alert_delivery_destinations",
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("is_tenant_default", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_test_at", sa.DateTime(), nullable=True),
        sa.Column("last_test_status", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.client_key"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("tenant_id", "id"),
    )
    op.create_table(
        "alert_fires",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column("alert_rule_id", sa.String(), nullable=False),
        sa.Column("destination_id", sa.String(), nullable=False),
        sa.Column("fired_at", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.client_key"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("alert_fires", schema=None) as batch_op:
        batch_op.create_index(
            "ix_alert_fires_lookup",
            ["tenant_id", "alert_rule_id", "destination_id", "fired_at"],
            unique=False,
        )

    op.create_table(
        "alert_rules",
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.client_key"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("tenant_id", "id"),
    )
    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column("rule_id", sa.String(), nullable=False),
        sa.Column("rule_type", sa.String(), nullable=False),
        sa.Column("issue_id", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("triggered_at", sa.DateTime(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.client_key"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "rule_id", "issue_id", "status", "key", name="uq_alert_idempotency"
        ),
    )
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.create_index("ix_alerts_triggered_at", ["tenant_id", "triggered_at"], unique=False)

    op.create_table(
        "issues",
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("project_key", sa.String(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("issue_type", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("done_at", sa.DateTime(), nullable=True),
        sa.Column("current_status", sa.String(), nullable=True),
        sa.Column("assignee", sa.String(), nullable=True),
        sa.Column("assignee_account_id", sa.String(), nullable=True),
        sa.Column("priority", sa.String(), nullable=True),
        sa.Column("story_points", sa.Float(), nullable=True),
        sa.Column("raw_payload", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.client_key"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("tenant_id", "id"),
    )
    with op.batch_alter_table("issues", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_issues_current_status"), ["current_status"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_issues_key"), ["key"], unique=False)
        batch_op.create_index("ix_issues_project", ["tenant_id", "project_key"], unique=False)

    op.create_table(
        "metrics_status_window",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("window_start", sa.DateTime(), nullable=False),
        sa.Column("window_end", sa.DateTime(), nullable=False),
        sa.Column("avg_seconds", sa.Float(), nullable=True),
        sa.Column("p50_seconds", sa.Float(), nullable=True),
        sa.Column("p90_seconds", sa.Float(), nullable=True),
        sa.Column("wip_avg", sa.Float(), nullable=True),
        sa.Column("throughput", sa.Integer(), nullable=True),
        sa.Column("sample_size", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.client_key"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "status", "window_start", "window_end", name="uq_status_window"
        ),
    )
    with op.batch_alter_table("metrics_status_window", schema=None) as batch_op:
        batch_op.create_index(
            "ix_status_window", ["tenant_id", "status", "window_start"], unique=False
        )

    op.create_table(
        "sprints",
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("start_at", sa.DateTime(), nullable=True),
        sa.Column("end_at", sa.DateTime(), nullable=True),
        sa.Column("complete_at", sa.DateTime(), nullable=True),
        sa.Column("board_id", sa.Integer(), nullable=False),
        sa.Column("project_key", sa.String(), nullable=True),
        sa.Column("raw_payload", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.client_key"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("tenant_id", "id"),
    )
    with op.batch_alter_table("sprints", schema=None) as batch_op:
        batch_op.create_index("ix_sprints_project", ["tenant_id", "project_key"], unique=False)
        batch_op.create_index("ix_sprints_state", ["tenant_id", "state"], unique=False)

    op.create_table(
        "wip_limits",
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column("project_key", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("max_in_progress", sa.Integer(), nullable=False),
        sa.Column("breach_minutes", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.client_key"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("tenant_id", "project_key", "status"),
    )
    with op.batch_alter_table("wip_limits", schema=None) as batch_op:
        batch_op.create_index("ix_wip_limits_project", ["tenant_id", "project_key"], unique=False)
        batch_op.create_index("ix_wip_limits_tenant", ["tenant_id"], unique=False)

    op.create_table(
        "alert_rule_destinations",
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column("alert_rule_id", sa.String(), nullable=False),
        sa.Column("destination_id", sa.String(), nullable=False),
        sa.Column("override_cooldown_seconds", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id", "alert_rule_id"],
            ["alert_rules.tenant_id", "alert_rules.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "destination_id"],
            ["alert_delivery_destinations.tenant_id", "alert_delivery_destinations.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "alert_rule_id", "destination_id"),
    )
    op.create_table(
        "issue_sprints",
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column("issue_id", sa.String(), nullable=False),
        sa.Column("sprint_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "issue_id"], ["issues.tenant_id", "issues.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "sprint_id"], ["sprints.tenant_id", "sprints.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("tenant_id", "issue_id", "sprint_id"),
    )
    with op.batch_alter_table("issue_sprints", schema=None) as batch_op:
        batch_op.create_index("ix_issue_sprints_sprint", ["tenant_id", "sprint_id"], unique=False)

    op.create_table(
        "metrics_issue",
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column("issue_id", sa.String(), nullable=False),
        sa.Column("cycle_seconds", sa.Integer(), nullable=True),
        sa.Column("active_seconds", sa.Integer(), nullable=True),
        sa.Column("wait_seconds", sa.Integer(), nullable=True),
        sa.Column("is_done", sa.Boolean(), nullable=False),
        sa.Column("computed_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "issue_id"], ["issues.tenant_id", "issues.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("tenant_id", "issue_id"),
    )
    op.create_table(
        "time_slices",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column("issue_id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("status_id", sa.String(), nullable=True),
        sa.Column("start_at", sa.DateTime(), nullable=False),
        sa.Column("end_at", sa.DateTime(), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=False),
        sa.Column("is_open", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "issue_id"], ["issues.tenant_id", "issues.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("time_slices", schema=None) as batch_op:
        batch_op.create_index(
            "ix_slices_issue_start", ["tenant_id", "issue_id", "start_at"], unique=False
        )
        batch_op.create_index(
            "ix_slices_status_id_start", ["tenant_id", "status_id", "start_at"], unique=False
        )
        batch_op.create_index(
            "ix_slices_status_start", ["tenant_id", "status", "start_at"], unique=False
        )

    op.create_table(
        "transitions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column("issue_id", sa.String(), nullable=False),
        sa.Column("from_status", sa.String(), nullable=True),
        sa.Column("to_status", sa.String(), nullable=True),
        sa.Column("from_status_id", sa.String(), nullable=True),
        sa.Column("to_status_id", sa.String(), nullable=True),
        sa.Column("transitioned_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "issue_id"], ["issues.tenant_id", "issues.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "issue_id", "transitioned_at", "to_status", name="uq_transition_dedupe"
        ),
    )
    with op.batch_alter_table("transitions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_transitions_issue_ts", ["tenant_id", "issue_id", "transitioned_at"], unique=False
        )
        batch_op.create_index(
            "ix_transitions_to_status_id", ["tenant_id", "to_status_id"], unique=False
        )

    # ### end Alembic commands ###

    # Defense-in-depth Postgres RLS (ADR-0011 / ADR-0014): pin every query on a
    # tenanted table to `current_setting('app.current_tenant')`. Service-layer
    # `WHERE tenant_id = ?` filtering is the primary guard; RLS is the safety
    # net. SQLite (test path) has no policies/GUCs, so this no-ops there.
    if _is_postgres():
        for table in _RLS_TENANTED_TABLES:
            _enable_rls(table)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if _is_postgres():
        for table in reversed(_RLS_TENANTED_TABLES):
            op.execute(f'DROP POLICY IF EXISTS tenant_isolation ON "{table}"')
            op.execute(f'ALTER TABLE "{table}" NO FORCE ROW LEVEL SECURITY')
            op.execute(f'ALTER TABLE "{table}" DISABLE ROW LEVEL SECURITY')

    with op.batch_alter_table("transitions", schema=None) as batch_op:
        batch_op.drop_index("ix_transitions_to_status_id")
        batch_op.drop_index("ix_transitions_issue_ts")

    op.drop_table("transitions")
    with op.batch_alter_table("time_slices", schema=None) as batch_op:
        batch_op.drop_index("ix_slices_status_start")
        batch_op.drop_index("ix_slices_status_id_start")
        batch_op.drop_index("ix_slices_issue_start")

    op.drop_table("time_slices")
    op.drop_table("metrics_issue")
    with op.batch_alter_table("issue_sprints", schema=None) as batch_op:
        batch_op.drop_index("ix_issue_sprints_sprint")

    op.drop_table("issue_sprints")
    op.drop_table("alert_rule_destinations")
    with op.batch_alter_table("wip_limits", schema=None) as batch_op:
        batch_op.drop_index("ix_wip_limits_tenant")
        batch_op.drop_index("ix_wip_limits_project")

    op.drop_table("wip_limits")
    with op.batch_alter_table("sprints", schema=None) as batch_op:
        batch_op.drop_index("ix_sprints_state")
        batch_op.drop_index("ix_sprints_project")

    op.drop_table("sprints")
    with op.batch_alter_table("metrics_status_window", schema=None) as batch_op:
        batch_op.drop_index("ix_status_window")

    op.drop_table("metrics_status_window")
    with op.batch_alter_table("issues", schema=None) as batch_op:
        batch_op.drop_index("ix_issues_project")
        batch_op.drop_index(batch_op.f("ix_issues_key"))
        batch_op.drop_index(batch_op.f("ix_issues_current_status"))

    op.drop_table("issues")
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.drop_index("ix_alerts_triggered_at")

    op.drop_table("alerts")
    op.drop_table("alert_rules")
    with op.batch_alter_table("alert_fires", schema=None) as batch_op:
        batch_op.drop_index("ix_alert_fires_lookup")

    op.drop_table("alert_fires")
    op.drop_table("alert_delivery_destinations")
    op.drop_table("work_schedules")
    with op.batch_alter_table("tenants", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tenants_cloud_id"))

    op.drop_table("tenants")
    # ### end Alembic commands ###
